CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE admins (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    passwordhash text NOT NULL,
    CONSTRAINT "PK_admins" PRIMARY KEY (id)
);

CREATE TABLE agents (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    agentname character varying(40) NOT NULL,
    agentpassword character varying(40) NOT NULL,
    agentopendate timestamp with time zone NOT NULL,
    CONSTRAINT "PK_agents" PRIMARY KEY (id)
);

CREATE TABLE checks (
    checkid integer NOT NULL,
    clientname character varying(100) NOT NULL,
    clientid integer NOT NULL,
    orderto character varying(100) NOT NULL,
    sum numeric(18,2) NOT NULL,
    transid integer NOT NULL,
    agentname character varying(100) NOT NULL,
    agentid integer NOT NULL,
    checkissueddate timestamp with time zone NOT NULL,
    CONSTRAINT "PK_checks" PRIMARY KEY (checkid)
);

CREATE TABLE clients (
    clientid integer GENERATED BY DEFAULT AS IDENTITY,
    clientfirstname character varying(40) NOT NULL,
    clientlastname character varying(40) NOT NULL,
    phonenumber character varying(18) NOT NULL,
    clientopendate timestamp with time zone NOT NULL,
    urav boolean NOT NULL,
    comments character varying(4000) NOT NULL,
    clientpassword text NULL,
    updatebyemail boolean NOT NULL,
    email character varying(255) NULL,
    selectedposition character varying(30) NOT NULL,
    agent text NOT NULL,
    CONSTRAINT "PK_clients" PRIMARY KEY (clientid)
);

CREATE TABLE updates (
    recordid integer GENERATED BY DEFAULT AS IDENTITY,
    tablename character varying(128) NOT NULL,
    objectid character varying(64) NOT NULL,
    columname character varying(128) NOT NULL,
    prevversion character varying(4000) NOT NULL,
    updatedversion character varying(4000) NOT NULL,
    agent character varying(100) NOT NULL,
    timestamp timestamp with time zone NOT NULL,
    CONSTRAINT "PK_updates" PRIMARY KEY (recordid)
);

CREATE TABLE accounts (
    accountid integer GENERATED BY DEFAULT AS IDENTITY,
    clientid integer NOT NULL,
    updatebaldate timestamp with time zone NOT NULL,
    totalamount numeric(18,2) NULL,
    CONSTRAINT "PK_accounts" PRIMARY KEY (accountid),
    CONSTRAINT "FK_accounts_clients_clientid" FOREIGN KEY (clientid) REFERENCES clients (clientid) ON DELETE CASCADE
);

CREATE TABLE transactions (
    transid integer GENERATED BY DEFAULT AS IDENTITY,
    clientid integer NOT NULL,
    transdate timestamp with time zone NOT NULL,
    agent character varying(40) NOT NULL,
    added numeric(18,2) NULL,
    subtracted numeric(18,2) NULL,
    totaladded numeric(18,2) NULL,
    totalsubtracted numeric(18,2) NULL,
    sendemail boolean NOT NULL,
    accountid integer NULL,
    CONSTRAINT "PK_transactions" PRIMARY KEY (transid),
    CONSTRAINT "FK_transactions_accounts_accountid" FOREIGN KEY (accountid) REFERENCES accounts (accountid),
    CONSTRAINT "FK_transactions_clients_clientid" FOREIGN KEY (clientid) REFERENCES clients (clientid) ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_accounts_clientid" ON accounts (clientid);

CREATE INDEX "IX_transactions_accountid" ON transactions (accountid);

CREATE INDEX "IX_transactions_clientid" ON transactions (clientid);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260111235407_InitialCreate', '6.0.36');

COMMIT;

